name: React CI/CD

on:
  push:
    branches:
      - main

jobs:
  react:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Node.js dependencies
        run: |
          cd chat-app-frontend
          npm install

      - name: Run React tests
        run: |
          cd chat-app-frontend
          npm test
